apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapscroll-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapscroll-api
  template:
    metadata:
      labels:
        app: snapscroll-api
        app.kubernetes.io/name: snapscroll-api
    spec:
      containers:
      - name: snapscroll-api-container
        image: ghcr.io/domints/snapscroll-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: Database__Username
          valueFrom:
            secretKeyRef:
              name: snapscroll-database
              key: username
        - name: Database__Password
          valueFrom:
            secretKeyRef:
              name: snapscroll-database
              key: password
        - name: Database__Host
          value: mariadb-1709158373
        - name: Database__Name
          value: snapscroll
        - name: DOTNET_ENVIRONMENT
          value: Development
      nodeSelector:
        kubernetes.io/arch: arm64