# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
    paths:
      - SnapScroll.Backend/**
      - .github/workflows/dotnet.yml
      - kubernetes/api/**
  pull_request:
    branches: [ "master" ]
    paths:
      - SnapScroll.Backend/**
      - .github/workflows/dotnet.yml
      - kubernetes/api/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-api

jobs:
  build:
    permissions: write-all

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SnapScroll.Frontend
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #- name: Restore dependencies
    #  run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore
    - name: Publish x64
      run: dotnet publish -c Release -a x64 -o ./out/amd64
    - name: Publish arm64
      run: dotnet publish -c Release -a arm64 -o ./out/arm64
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=ref,event=branch
          type=sha,format=long
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./SnapScroll.Frontend
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SnapScroll.Frontend

    steps:
      - uses: actions/checkout@v3
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ vars.KUBERNETES_ADDRESS }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Set Image Identifier
        run: |
          echo "IMAGE=${{ env.REGISTRY }}/${IMG_NAME@L}:sha-${{ github.sha }}" >> ${GITHUB_ENV}
        env:
          IMG_NAME: ${{ env.IMAGE_NAME }}
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          action: deploy
          namespace: snapscroll
          manifests: |
            kubernetes/api/deployment.yaml
            kubernetes/api/ingress.yaml
            kubernetes/api/service.yaml
          strategy: 'basic'
          images: |
            ${{ env.IMAGE }}